#!/usr/bin/env bash
# Generated by LMAppStore — re-installs previously installed packages

# APT packages
sudo apt install -y \
  azure-cli \
  bind9-dnsutils \
  bridge-utils \
  build-essential \
  cabextract \
  code \
  code-insiders \
  cpu-checker \
  curl \
  dconf-cli \
  displaylink-driver \
  dkms \
  dotnet-sdk-10.0 \
  dpkg-repack \
  drawing \
  eslint \
  fastfetch \
  gdb \
  gh \
  git \
  gpick \
  grub-customizer \
  gufw \
  hardinfo \
  html2text \
  hwinfo \
  iat \
  ideviceinstaller \
  ifuse \
  imagemagick \
  inetutils-telnet \
  inxi \
  lm-sensors \
  ltrace \
  mesa-utils \
  mintchat \
  mpv \
  msr-tools \
  mtr-tiny \
  nala \
  nano \
  neofetch \
  net-tools \
  netcat-openbsd \
  nodejs \
  npm \
  nvidia-driver-570 \
  nvidia-prime \
  nvidia-prime-applet \
  openvpn \
  os-prober \
  ovmf \
  packagekit-tools \
  packages-microsoft-prod \
  papirus-icon-theme \
  patchutils \
  poppler-utils \
  powershell \
  pptp-linux \
  python3-pip \
  python3-venv \
  qemu-system-x86 \
  qemu-utils \
  qterminal \
  rename \
  rsync \
  rustc \
  shutter \
  solaar \
  strace \
  sysstat \
  tcpdump \
  terminator \
  touchegg \
  ttf-mscorefonts-installer \
  unzip \
  vainfo \
  vdpauinfo \
  virt-manager \
  virt-viewer \
  virtinst \
  vulkan-tools \
  wmctrl \
  xclip \
  yt-dlp \
  zip

# Flatpak packages
flatpak install -y io.github.celluloid_player.Celluloid
flatpak install -y org.strawberrymusicplayer.strawberry
flatpak install -y com.jgraph.drawio.desktop
flatpak install -y org.gnome.Papers
flatpak install -y org.kde.kleopatra
flatpak install -y com.getpostman.Postman
flatpak install -y org.kde.kdenlive
flatpak install -y com.obsproject.Studio
flatpak install -y app.devsuite.Ptyxis
flatpak install -y com.brave.Browser
flatpak install -y org.localsend.localsend_app
flatpak install -y org.gnome.Loupe
flatpak install -y org.kde.kpat
flatpak install -y de.haeckerfelix.Shortwave
flatpak install -y org.kde.isoimagewriter
flatpak install -y com.bitwarden.desktop
flatpak install -y net.puddletag.puddletag
flatpak install -y com.slack.Slack
flatpak install -y org.qbittorrent.qBittorrent
flatpak install -y md.obsidian.Obsidian
flatpak install -y io.github.shiftey.Desktop
flatpak install -y org.gimp.GIMP
flatpak install -y org.nickvision.tubeconverter
flatpak install -y com.github.IsmaelMartinez.teams_for_linux
flatpak install -y org.telegram.desktop
flatpak install -y org.torproject.torbrowser-launcher
